Planeje_UnB/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :disciplinas


  devise_scope :user do
  	authenticated :user do
    	root 'home#home', as: :authenticated_root
  	end

  	unauthenticated do
    	root 'devise/sessions#new', as: :unauthenticated_root
  	end
  end

  post "semestre" => "home#semestre"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Planeje_UnB/app/models/disciplina.rb
class Disciplina < ApplicationRecord
	serialize :pre_requisito
	serialize :semestre

	has_and_belongs_to_many :users

	validates_uniqueness_of :nome, :message => "já existente"
	validates_presence_of :nome, :creditos, :categoria, message: 'não pode ser deixado em branco'
	validates_length_of :creditos, in: 1..2, message: "fora do intervalo permitido"
	validates_numericality_of :creditos, message: "deve ser numero"
end

Planeje_UnB/app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: [:show, :edit, :update, :destroy]

  # GET /disciplinas
  # GET /disciplinas.json
  def index
    @disciplinas = Disciplina.all
  end

  # GET /disciplinas/1
  # GET /disciplinas/1.json
  def show
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas
  # POST /disciplinas.json
  def create
    @disciplina = Disciplina.new(disciplina_params)

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to @disciplina, notice: 'Disciplina foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1
  # PATCH/PUT /disciplinas/1.json
  def update
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to @disciplina, notice: 'Disciplina foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1
  # DELETE /disciplinas/1.json
  def destroy
    @disciplina.destroy
    respond_to do |format|
      format.html { redirect_to disciplinas_url, notice: 'Disciplina foi removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disciplina_params
      params.require(:disciplina).permit(:nome, :mencao, :pre_requisito, :creditos, :categoria)
    end
end

Planeje_UnB/app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

Planeje_UnB/app/views/disciplinas/_form.html.erb
<%= form_for(disciplina) do |f| %>
  <% if disciplina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(disciplina.errors.count, "error") %> prohibited this disciplina from being saved:</h2>

      <ul>
      <% disciplina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>
  
  <div class="field">
    <%= f.label :pre_requisito %>
    <%= f.text_field :pre_requisito %>
  </div>

  <div class="field">
    <%= f.label :creditos %>
    <%= f.number_field :creditos %>
  </div>

  <div class="field">
    <%= f.label :categoria %>
    <%= f.text_field :categoria %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Planeje_UnB/app/views/disciplinas/edit.html.erb
  <nav style="height: 80px;">
    <div class="nav-wrapper #1a237e indigo darken-4">
      <a href="/" class="brand-logo left">Início</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        
        <li><a class="notice"><%= notice %></a>
         <a class="alert"><%= alert %></a></li>


        <li><a class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Se inscrever", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Entrar", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </a></li>
        
      </ul>
    </div>
  </nav>
  
<h1>Editando Disciplina</h1>

<%= render 'form', disciplina: @disciplina %>

<%= link_to 'Mostrar', @disciplina %> |
<%= link_to 'Voltar', disciplinas_path %>

Planeje_UnB/app/views/disciplinas/index.html.erb
 <nav style="height: 80px;">
    <div class="nav-wrapper #1a237e indigo darken-4">
      <a href="/" class="brand-logo left">Início</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        
        <li><a class="notice"><%= notice %></a>
         <a class="alert"><%= alert %></a></li>


        <li><a class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Se inscrever", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Entrar", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </a></li>
        
      </ul>
    </div>
  </nav>
  
<p id="notice"><%= notice %></p>

<h1>Disciplinas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Pre requisito</th>
      <th>Creditos</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplinas.each do |disciplina| %>
      <tr>
        <td><%= disciplina.nome %></td>
        <td><%= disciplina.pre_requisito %></td>
        <td><%= disciplina.creditos %></td>
        <td><%= disciplina.categoria %></td>
        <td><%= link_to 'Mostrar', disciplina %></td>
        <td><%= link_to 'Editar', edit_disciplina_path(disciplina) %></td>
        <td><%= link_to 'Remover', disciplina, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Disciplina', new_disciplina_path %>

Planeje_UnB/app/views/disciplinas/new.html.erb
  <nav style="height: 80px;">
    <div class="nav-wrapper #1a237e indigo darken-4">
      <a href="/" class="brand-logo left">Início</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        
        <li><a class="notice"><%= notice %></a>
         <a class="alert"><%= alert %></a></li>


        <li><a class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Se inscrever", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Entrar", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </a></li>
        
      </ul>
    </div>
  </nav>

<h1>Cadastrar Disciplina</h1>

<%= render 'form', disciplina: @disciplina %>

<%= link_to 'Voltar', disciplinas_path %>

Planeje_UnB/app/views/disciplinas/show.html.erb
  <nav style="height: 80px;">
    <div class="nav-wrapper #1a237e indigo darken-4">
      <a href="/" class="brand-logo left">Início</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        
        <li><a class="notice"><%= notice %></a>
         <a class="alert"><%= alert %></a></li>


        <li><a class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Se inscrever", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Entrar", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </a></li>
        
      </ul>
    </div>
  </nav>
  
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @disciplina.nome %>
</p>

<p>
  <strong>Pre requisito:</strong>
  <%= @disciplina.pre_requisito %>
</p>

<p>
  <strong>Creditos:</strong>
  <%= @disciplina.creditos %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @disciplina.categoria %>
</p>

<%= link_to 'Editar', edit_disciplina_path(@disciplina) %> |
<%= link_to 'Voltar', disciplinas_path %>